"""add media table

Revision ID: 334d08735c8e
Revises: 089147d0446c
Create Date: 2026-07-18 22:43:30.709236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '334d08735c8e'
down_revision: Union[str, Sequence[str], None] = '089147d0446c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_media_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.String(length=20), server_default='image', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='generation', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('scope_type', sa.String(length=20), server_default='', nullable=False),
    sa.Column('scope_public_id', sa.String(length=36), server_default='', nullable=False),
    sa.Column('media_role', sa.String(length=40), server_default='generated', nullable=False),
    sa.Column('provider_key', sa.String(length=80), server_default='', nullable=False),
    sa.Column('model_id', sa.String(length=120), server_default='', nullable=False),
    sa.Column('prompt', sa.Text(), server_default='', nullable=False),
    sa.Column('params', sa.Text(), server_default='{}', nullable=False),
    sa.Column('seed', sa.String(length=60), server_default='', nullable=False),
    sa.Column('storage_backend', sa.String(length=20), server_default='', nullable=False),
    sa.Column('storage_key', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('url', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('mime_type', sa.String(length=120), server_default='', nullable=False),
    sa.Column('file_size', sa.Integer(), server_default='0', nullable=False),
    sa.Column('width', sa.Integer(), server_default='0', nullable=False),
    sa.Column('height', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('usage', sa.Text(), server_default='{}', nullable=False),
    sa.Column('task_job_public_id', sa.String(length=36), server_default='', nullable=False),
    sa.Column('task_item_public_id', sa.String(length=36), server_default='', nullable=False),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_media_asset_disabled_at'), 'af_media_asset', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_media_asset_media_role'), 'af_media_asset', ['media_role'], unique=False)
    op.create_index(op.f('ix_af_media_asset_media_type'), 'af_media_asset', ['media_type'], unique=False)
    op.create_index(op.f('ix_af_media_asset_model_id'), 'af_media_asset', ['model_id'], unique=False)
    op.create_index(op.f('ix_af_media_asset_project_id'), 'af_media_asset', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_media_asset_provider_key'), 'af_media_asset', ['provider_key'], unique=False)
    op.create_index(op.f('ix_af_media_asset_public_id'), 'af_media_asset', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_media_asset_scope_public_id'), 'af_media_asset', ['scope_public_id'], unique=False)
    op.create_index(op.f('ix_af_media_asset_scope_type'), 'af_media_asset', ['scope_type'], unique=False)
    op.create_index(op.f('ix_af_media_asset_sort_order'), 'af_media_asset', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_media_asset_source'), 'af_media_asset', ['source'], unique=False)
    op.create_index(op.f('ix_af_media_asset_status'), 'af_media_asset', ['status'], unique=False)
    op.create_index(op.f('ix_af_media_asset_storage_key'), 'af_media_asset', ['storage_key'], unique=False)
    op.create_index(op.f('ix_af_media_asset_task_item_public_id'), 'af_media_asset', ['task_item_public_id'], unique=False)
    op.create_index(op.f('ix_af_media_asset_task_job_public_id'), 'af_media_asset', ['task_job_public_id'], unique=False)
    op.create_index(op.f('ix_af_media_asset_user_public_id'), 'af_media_asset', ['user_public_id'], unique=False)
    op.drop_index(op.f('ix_af_asset_generation_asset_id'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_disabled_at'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_generation_type'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_model_id'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_project_id'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_provider'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_public_id'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_sort_order'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_status'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_task_item_public_id'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_task_job_public_id'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_user_public_id'), table_name='af_asset_generation')
    op.drop_table('af_asset_generation')
    op.drop_index(op.f('ix_af_asset_media_asset_id'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_disabled_at'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_generation_public_id'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_media_role'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_media_type'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_project_id'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_public_id'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_sort_order'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_storage_key'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_user_public_id'), table_name='af_asset_media')
    op.drop_table('af_asset_media')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_asset_media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('disabled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_public_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=20), server_default=sa.text("'image'::character varying"), autoincrement=False, nullable=False),
    sa.Column('media_role', sa.VARCHAR(length=40), server_default=sa.text("'reference'::character varying"), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=2000), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(length=1000), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('generation_public_id', sa.VARCHAR(length=36), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('extra_data', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['af_asset.id'], name=op.f('af_asset_media_asset_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], name=op.f('af_asset_media_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('af_asset_media_pkey'))
    )
    op.create_index(op.f('ix_af_asset_media_user_public_id'), 'af_asset_media', ['user_public_id'], unique=False)
    op.create_index(op.f('ix_af_asset_media_storage_key'), 'af_asset_media', ['storage_key'], unique=False)
    op.create_index(op.f('ix_af_asset_media_sort_order'), 'af_asset_media', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_asset_media_public_id'), 'af_asset_media', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_asset_media_project_id'), 'af_asset_media', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_asset_media_media_type'), 'af_asset_media', ['media_type'], unique=False)
    op.create_index(op.f('ix_af_asset_media_media_role'), 'af_asset_media', ['media_role'], unique=False)
    op.create_index(op.f('ix_af_asset_media_generation_public_id'), 'af_asset_media', ['generation_public_id'], unique=False)
    op.create_index(op.f('ix_af_asset_media_disabled_at'), 'af_asset_media', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_asset_media_asset_id'), 'af_asset_media', ['asset_id'], unique=False)
    op.create_table('af_asset_generation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('disabled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_public_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_type', sa.VARCHAR(length=40), server_default=sa.text("'image'::character varying"), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=80), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('negative_prompt', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('parameters', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('task_job_public_id', sa.VARCHAR(length=36), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('task_item_public_id', sa.VARCHAR(length=36), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('output', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['af_asset.id'], name=op.f('af_asset_generation_asset_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], name=op.f('af_asset_generation_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('af_asset_generation_pkey'))
    )
    op.create_index(op.f('ix_af_asset_generation_user_public_id'), 'af_asset_generation', ['user_public_id'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_task_job_public_id'), 'af_asset_generation', ['task_job_public_id'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_task_item_public_id'), 'af_asset_generation', ['task_item_public_id'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_status'), 'af_asset_generation', ['status'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_sort_order'), 'af_asset_generation', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_public_id'), 'af_asset_generation', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_asset_generation_provider'), 'af_asset_generation', ['provider'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_project_id'), 'af_asset_generation', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_model_id'), 'af_asset_generation', ['model_id'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_generation_type'), 'af_asset_generation', ['generation_type'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_disabled_at'), 'af_asset_generation', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_asset_id'), 'af_asset_generation', ['asset_id'], unique=False)
    op.drop_index(op.f('ix_af_media_asset_user_public_id'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_task_job_public_id'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_task_item_public_id'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_storage_key'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_status'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_source'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_sort_order'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_scope_type'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_scope_public_id'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_public_id'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_provider_key'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_project_id'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_model_id'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_media_type'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_media_role'), table_name='af_media_asset')
    op.drop_index(op.f('ix_af_media_asset_disabled_at'), table_name='af_media_asset')
    op.drop_table('af_media_asset')
    # ### end Alembic commands ###
