"""project  table add art style and derector style field

Revision ID: 3856a097d10d
Revises: 334d08735c8e
Create Date: 2026-07-19 11:26:21.891022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3856a097d10d'
down_revision: Union[str, Sequence[str], None] = '334d08735c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('af_project', sa.Column('art_style_prompt', sa.Text(), server_default='', nullable=False))
    op.add_column('af_project', sa.Column('director_style_prompt', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('af_project', 'director_style_prompt')
    op.drop_column('af_project', 'art_style_prompt')
    # ### end Alembic commands ###
