"""create task dead letter table

Revision ID: 3b6648ba3734
Revises: e107d7f2328d
Create Date: 2026-07-15 16:15:33.084849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3b6648ba3734'
down_revision: Union[str, Sequence[str], None] = 'e107d7f2328d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_task_dead_letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('job_public_id', sa.String(length=36), server_default='', nullable=False),
    sa.Column('item_public_id', sa.String(length=36), server_default='', nullable=False),
    sa.Column('task_type', sa.String(length=100), server_default='', nullable=False),
    sa.Column('item_type', sa.String(length=100), server_default='', nullable=False),
    sa.Column('queue_name', sa.String(length=120), server_default='default', nullable=False),
    sa.Column('stream_id', sa.String(length=120), server_default='', nullable=False),
    sa.Column('stage', sa.String(length=100), server_default='', nullable=False),
    sa.Column('worker_id', sa.String(length=120), server_default='', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_code', sa.String(length=100), server_default='', nullable=False),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.Column('payload', sa.Text(), server_default='{}', nullable=False),
    sa.Column('result', sa.Text(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['af_task_item.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['af_task_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_task_dead_letter_disabled_at'), 'af_task_dead_letter', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_task_dead_letter_item_id'), 'af_task_dead_letter', ['item_id'], unique=False)
    op.create_index(op.f('ix_af_task_dead_letter_item_public_id'), 'af_task_dead_letter', ['item_public_id'], unique=False)
    op.create_index(op.f('ix_af_task_dead_letter_item_type'), 'af_task_dead_letter', ['item_type'], unique=False)
    op.create_index(op.f('ix_af_task_dead_letter_job_id'), 'af_task_dead_letter', ['job_id'], unique=False)
    op.create_index(op.f('ix_af_task_dead_letter_job_public_id'), 'af_task_dead_letter', ['job_public_id'], unique=False)
    op.create_index(op.f('ix_af_task_dead_letter_public_id'), 'af_task_dead_letter', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_task_dead_letter_queue_name'), 'af_task_dead_letter', ['queue_name'], unique=False)
    op.create_index(op.f('ix_af_task_dead_letter_sort_order'), 'af_task_dead_letter', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_task_dead_letter_stage'), 'af_task_dead_letter', ['stage'], unique=False)
    op.create_index(op.f('ix_af_task_dead_letter_stream_id'), 'af_task_dead_letter', ['stream_id'], unique=False)
    op.create_index(op.f('ix_af_task_dead_letter_task_type'), 'af_task_dead_letter', ['task_type'], unique=False)
    op.create_index(op.f('ix_af_task_dead_letter_worker_id'), 'af_task_dead_letter', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_task_dead_letter_worker_id'), table_name='af_task_dead_letter')
    op.drop_index(op.f('ix_af_task_dead_letter_task_type'), table_name='af_task_dead_letter')
    op.drop_index(op.f('ix_af_task_dead_letter_stream_id'), table_name='af_task_dead_letter')
    op.drop_index(op.f('ix_af_task_dead_letter_stage'), table_name='af_task_dead_letter')
    op.drop_index(op.f('ix_af_task_dead_letter_sort_order'), table_name='af_task_dead_letter')
    op.drop_index(op.f('ix_af_task_dead_letter_queue_name'), table_name='af_task_dead_letter')
    op.drop_index(op.f('ix_af_task_dead_letter_public_id'), table_name='af_task_dead_letter')
    op.drop_index(op.f('ix_af_task_dead_letter_job_public_id'), table_name='af_task_dead_letter')
    op.drop_index(op.f('ix_af_task_dead_letter_job_id'), table_name='af_task_dead_letter')
    op.drop_index(op.f('ix_af_task_dead_letter_item_type'), table_name='af_task_dead_letter')
    op.drop_index(op.f('ix_af_task_dead_letter_item_public_id'), table_name='af_task_dead_letter')
    op.drop_index(op.f('ix_af_task_dead_letter_item_id'), table_name='af_task_dead_letter')
    op.drop_index(op.f('ix_af_task_dead_letter_disabled_at'), table_name='af_task_dead_letter')
    op.drop_table('af_task_dead_letter')
    # ### end Alembic commands ###
