"""add asset tables (asset, episode, relation, version, media, generation)

Revision ID: 4f2c2958a5f7
Revises: d870b826d913
Create Date: 2026-07-17 13:07:15.363725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4f2c2958a5f7'
down_revision: Union[str, Sequence[str], None] = 'd870b826d913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=20), server_default='role', nullable=False),
    sa.Column('name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('keyword', sa.String(length=500), server_default='', nullable=False),
    sa.Column('colors', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('details', sa.Text(), server_default='{}', nullable=False),
    sa.Column('accessories', sa.Text(), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('main_asset', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('variant_label', sa.String(length=100), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_public_id', 'asset_type', 'name', name='uq_af_asset_project_user_type_name')
    )
    op.create_index(op.f('ix_af_asset_asset_type'), 'af_asset', ['asset_type'], unique=False)
    op.create_index(op.f('ix_af_asset_disabled_at'), 'af_asset', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_asset_main_asset'), 'af_asset', ['main_asset'], unique=False)
    op.create_index(op.f('ix_af_asset_project_id'), 'af_asset', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_asset_public_id'), 'af_asset', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_asset_sort_order'), 'af_asset', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_asset_status'), 'af_asset', ['status'], unique=False)
    op.create_index(op.f('ix_af_asset_user_public_id'), 'af_asset', ['user_public_id'], unique=False)
    op.create_table('af_asset_generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('generation_type', sa.String(length=40), server_default='image', nullable=False),
    sa.Column('provider', sa.String(length=80), server_default='', nullable=False),
    sa.Column('model_id', sa.String(length=120), server_default='', nullable=False),
    sa.Column('prompt', sa.Text(), server_default='', nullable=False),
    sa.Column('negative_prompt', sa.Text(), server_default='', nullable=False),
    sa.Column('parameters', sa.Text(), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('task_job_public_id', sa.String(length=36), server_default='', nullable=False),
    sa.Column('task_item_public_id', sa.String(length=36), server_default='', nullable=False),
    sa.Column('output', sa.Text(), server_default='{}', nullable=False),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['af_asset.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_asset_generation_asset_id'), 'af_asset_generation', ['asset_id'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_disabled_at'), 'af_asset_generation', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_generation_type'), 'af_asset_generation', ['generation_type'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_model_id'), 'af_asset_generation', ['model_id'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_project_id'), 'af_asset_generation', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_provider'), 'af_asset_generation', ['provider'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_public_id'), 'af_asset_generation', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_asset_generation_sort_order'), 'af_asset_generation', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_status'), 'af_asset_generation', ['status'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_task_item_public_id'), 'af_asset_generation', ['task_item_public_id'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_task_job_public_id'), 'af_asset_generation', ['task_job_public_id'], unique=False)
    op.create_index(op.f('ix_af_asset_generation_user_public_id'), 'af_asset_generation', ['user_public_id'], unique=False)
    op.create_table('af_asset_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), server_default='image', nullable=False),
    sa.Column('media_role', sa.String(length=40), server_default='reference', nullable=False),
    sa.Column('url', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('storage_key', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('mime_type', sa.String(length=120), server_default='', nullable=False),
    sa.Column('width', sa.Integer(), server_default='0', nullable=False),
    sa.Column('height', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('prompt', sa.Text(), server_default='', nullable=False),
    sa.Column('generation_public_id', sa.String(length=36), server_default='', nullable=False),
    sa.Column('extra_data', sa.Text(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['af_asset.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_asset_media_asset_id'), 'af_asset_media', ['asset_id'], unique=False)
    op.create_index(op.f('ix_af_asset_media_disabled_at'), 'af_asset_media', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_asset_media_generation_public_id'), 'af_asset_media', ['generation_public_id'], unique=False)
    op.create_index(op.f('ix_af_asset_media_media_role'), 'af_asset_media', ['media_role'], unique=False)
    op.create_index(op.f('ix_af_asset_media_media_type'), 'af_asset_media', ['media_type'], unique=False)
    op.create_index(op.f('ix_af_asset_media_project_id'), 'af_asset_media', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_asset_media_public_id'), 'af_asset_media', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_asset_media_sort_order'), 'af_asset_media', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_asset_media_storage_key'), 'af_asset_media', ['storage_key'], unique=False)
    op.create_index(op.f('ix_af_asset_media_user_public_id'), 'af_asset_media', ['user_public_id'], unique=False)
    op.create_table('af_asset_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_asset_id', sa.Integer(), nullable=False),
    sa.Column('target_asset_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=40), server_default='appears_with', nullable=False),
    sa.Column('relation_label', sa.String(length=120), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['source_asset_id'], ['af_asset.id'], ),
    sa.ForeignKeyConstraint(['target_asset_id'], ['af_asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_asset_id', 'target_asset_id', 'relation_type', name='uq_af_asset_relation_source_target_type')
    )
    op.create_index(op.f('ix_af_asset_relation_disabled_at'), 'af_asset_relation', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_asset_relation_public_id'), 'af_asset_relation', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_asset_relation_relation_type'), 'af_asset_relation', ['relation_type'], unique=False)
    op.create_index(op.f('ix_af_asset_relation_sort_order'), 'af_asset_relation', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_asset_relation_source_asset_id'), 'af_asset_relation', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_af_asset_relation_target_asset_id'), 'af_asset_relation', ['target_asset_id'], unique=False)
    op.create_table('af_asset_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('snapshot', sa.Text(), server_default='{}', nullable=False),
    sa.Column('change_note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.String(length=36), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['af_asset.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'version', name='uq_af_asset_version_asset_version')
    )
    op.create_index(op.f('ix_af_asset_version_asset_id'), 'af_asset_version', ['asset_id'], unique=False)
    op.create_index(op.f('ix_af_asset_version_created_by'), 'af_asset_version', ['created_by'], unique=False)
    op.create_index(op.f('ix_af_asset_version_disabled_at'), 'af_asset_version', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_asset_version_project_id'), 'af_asset_version', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_asset_version_public_id'), 'af_asset_version', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_asset_version_sort_order'), 'af_asset_version', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_asset_version_user_public_id'), 'af_asset_version', ['user_public_id'], unique=False)
    op.create_table('af_asset_episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('episode_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source', sa.String(length=40), server_default='extraction', nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['af_asset.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['af_script_episode.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'episode_id', name='uq_af_asset_episode_asset_episode')
    )
    op.create_index(op.f('ix_af_asset_episode_asset_id'), 'af_asset_episode', ['asset_id'], unique=False)
    op.create_index(op.f('ix_af_asset_episode_disabled_at'), 'af_asset_episode', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_asset_episode_episode_id'), 'af_asset_episode', ['episode_id'], unique=False)
    op.create_index(op.f('ix_af_asset_episode_episode_index'), 'af_asset_episode', ['episode_index'], unique=False)
    op.create_index(op.f('ix_af_asset_episode_project_id'), 'af_asset_episode', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_asset_episode_public_id'), 'af_asset_episode', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_asset_episode_sort_order'), 'af_asset_episode', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_asset_episode_source'), 'af_asset_episode', ['source'], unique=False)
    op.create_index(op.f('ix_af_asset_episode_user_public_id'), 'af_asset_episode', ['user_public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_asset_episode_user_public_id'), table_name='af_asset_episode')
    op.drop_index(op.f('ix_af_asset_episode_source'), table_name='af_asset_episode')
    op.drop_index(op.f('ix_af_asset_episode_sort_order'), table_name='af_asset_episode')
    op.drop_index(op.f('ix_af_asset_episode_public_id'), table_name='af_asset_episode')
    op.drop_index(op.f('ix_af_asset_episode_project_id'), table_name='af_asset_episode')
    op.drop_index(op.f('ix_af_asset_episode_episode_index'), table_name='af_asset_episode')
    op.drop_index(op.f('ix_af_asset_episode_episode_id'), table_name='af_asset_episode')
    op.drop_index(op.f('ix_af_asset_episode_disabled_at'), table_name='af_asset_episode')
    op.drop_index(op.f('ix_af_asset_episode_asset_id'), table_name='af_asset_episode')
    op.drop_table('af_asset_episode')
    op.drop_index(op.f('ix_af_asset_version_user_public_id'), table_name='af_asset_version')
    op.drop_index(op.f('ix_af_asset_version_sort_order'), table_name='af_asset_version')
    op.drop_index(op.f('ix_af_asset_version_public_id'), table_name='af_asset_version')
    op.drop_index(op.f('ix_af_asset_version_project_id'), table_name='af_asset_version')
    op.drop_index(op.f('ix_af_asset_version_disabled_at'), table_name='af_asset_version')
    op.drop_index(op.f('ix_af_asset_version_created_by'), table_name='af_asset_version')
    op.drop_index(op.f('ix_af_asset_version_asset_id'), table_name='af_asset_version')
    op.drop_table('af_asset_version')
    op.drop_index(op.f('ix_af_asset_relation_target_asset_id'), table_name='af_asset_relation')
    op.drop_index(op.f('ix_af_asset_relation_source_asset_id'), table_name='af_asset_relation')
    op.drop_index(op.f('ix_af_asset_relation_sort_order'), table_name='af_asset_relation')
    op.drop_index(op.f('ix_af_asset_relation_relation_type'), table_name='af_asset_relation')
    op.drop_index(op.f('ix_af_asset_relation_public_id'), table_name='af_asset_relation')
    op.drop_index(op.f('ix_af_asset_relation_disabled_at'), table_name='af_asset_relation')
    op.drop_table('af_asset_relation')
    op.drop_index(op.f('ix_af_asset_media_user_public_id'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_storage_key'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_sort_order'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_public_id'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_project_id'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_media_type'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_media_role'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_generation_public_id'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_disabled_at'), table_name='af_asset_media')
    op.drop_index(op.f('ix_af_asset_media_asset_id'), table_name='af_asset_media')
    op.drop_table('af_asset_media')
    op.drop_index(op.f('ix_af_asset_generation_user_public_id'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_task_job_public_id'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_task_item_public_id'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_status'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_sort_order'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_public_id'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_provider'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_project_id'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_model_id'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_generation_type'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_disabled_at'), table_name='af_asset_generation')
    op.drop_index(op.f('ix_af_asset_generation_asset_id'), table_name='af_asset_generation')
    op.drop_table('af_asset_generation')
    op.drop_index(op.f('ix_af_asset_user_public_id'), table_name='af_asset')
    op.drop_index(op.f('ix_af_asset_status'), table_name='af_asset')
    op.drop_index(op.f('ix_af_asset_sort_order'), table_name='af_asset')
    op.drop_index(op.f('ix_af_asset_public_id'), table_name='af_asset')
    op.drop_index(op.f('ix_af_asset_project_id'), table_name='af_asset')
    op.drop_index(op.f('ix_af_asset_main_asset'), table_name='af_asset')
    op.drop_index(op.f('ix_af_asset_disabled_at'), table_name='af_asset')
    op.drop_index(op.f('ix_af_asset_asset_type'), table_name='af_asset')
    op.drop_table('af_asset')
    # ### end Alembic commands ###
