"""add video editor table

Revision ID: 5bd5cf8b0a39
Revises: 6f5a2aea74f6
Create Date: 2026-07-20 13:42:03.627812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5bd5cf8b0a39'
down_revision: Union[str, Sequence[str], None] = '6f5a2aea74f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_editor_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), server_default='剪辑工程', nullable=False),
    sa.Column('timeline', sa.Text(), server_default='{}', nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ratio', sa.String(length=20), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_af_editor_project_project')
    )
    op.create_index(op.f('ix_af_editor_project_disabled_at'), 'af_editor_project', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_editor_project_project_id'), 'af_editor_project', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_editor_project_public_id'), 'af_editor_project', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_editor_project_sort_order'), 'af_editor_project', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_editor_project_user_public_id'), 'af_editor_project', ['user_public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_editor_project_user_public_id'), table_name='af_editor_project')
    op.drop_index(op.f('ix_af_editor_project_sort_order'), table_name='af_editor_project')
    op.drop_index(op.f('ix_af_editor_project_public_id'), table_name='af_editor_project')
    op.drop_index(op.f('ix_af_editor_project_project_id'), table_name='af_editor_project')
    op.drop_index(op.f('ix_af_editor_project_disabled_at'), table_name='af_editor_project')
    op.drop_table('af_editor_project')
    # ### end Alembic commands ###
