"""storyboard shot table and first frame and last frame

Revision ID: 6f5a2aea74f6
Revises: eb68be0a1b86
Create Date: 2026-07-20 13:33:14.954663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6f5a2aea74f6'
down_revision: Union[str, Sequence[str], None] = 'eb68be0a1b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('af_storyboard_shot', sa.Column('first_frame_media_public_id', sa.String(length=36), server_default='', nullable=False))
    op.add_column('af_storyboard_shot', sa.Column('last_frame_media_public_id', sa.String(length=36), server_default='', nullable=False))
    op.create_index(op.f('ix_af_storyboard_shot_first_frame_media_public_id'), 'af_storyboard_shot', ['first_frame_media_public_id'], unique=False)
    op.create_index(op.f('ix_af_storyboard_shot_last_frame_media_public_id'), 'af_storyboard_shot', ['last_frame_media_public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_storyboard_shot_last_frame_media_public_id'), table_name='af_storyboard_shot')
    op.drop_index(op.f('ix_af_storyboard_shot_first_frame_media_public_id'), table_name='af_storyboard_shot')
    op.drop_column('af_storyboard_shot', 'last_frame_media_public_id')
    op.drop_column('af_storyboard_shot', 'first_frame_media_public_id')
    # ### end Alembic commands ###
