"""create project table

Revision ID: 8117da46bf39
Revises: b4d6dc639248
Create Date: 2026-05-13 16:57:30.948784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8117da46bf39'
down_revision: Union[str, Sequence[str], None] = 'b4d6dc639248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('intro', sa.String(length=2000), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('art_style', sa.String(length=100), nullable=False),
    sa.Column('director_manual', sa.String(length=4000), nullable=False),
    sa.Column('video_ratio', sa.String(length=20), nullable=False),
    sa.Column('image_model', sa.String(length=100), nullable=False),
    sa.Column('video_model', sa.String(length=100), nullable=False),
    sa.Column('image_quality', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_project_name'), 'af_project', ['name'], unique=False)
    op.create_index(op.f('ix_af_project_owner_id'), 'af_project', ['owner_id'], unique=False)
    op.create_index(op.f('ix_af_project_public_id'), 'af_project', ['public_id'], unique=True)
    op.create_table('af_project_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_project_member_project_id'), 'af_project_member', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_project_member_user_public_id'), 'af_project_member', ['user_public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_project_member_user_public_id'), table_name='af_project_member')
    op.drop_index(op.f('ix_af_project_member_project_id'), table_name='af_project_member')
    op.drop_table('af_project_member')
    op.drop_index(op.f('ix_af_project_public_id'), table_name='af_project')
    op.drop_index(op.f('ix_af_project_owner_id'), table_name='af_project')
    op.drop_index(op.f('ix_af_project_name'), table_name='af_project')
    op.drop_table('af_project')
    # ### end Alembic commands ###
