"""add screenwriting_session table

Revision ID: 876790dceb98
Revises: 3b6648ba3734
Create Date: 2026-07-16 10:31:55.847464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '876790dceb98'
down_revision: Union[str, Sequence[str], None] = '3b6648ba3734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_screenwriting_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(length=36), nullable=False),
    sa.Column('isolation_key', sa.String(length=180), nullable=False),
    sa.Column('conversation_id', sa.String(length=120), server_default='', nullable=False),
    sa.Column('model_id', sa.String(length=100), server_default='', nullable=False),
    sa.Column('active_tab', sa.String(length=40), server_default='skeleton', nullable=False),
    sa.Column('skeleton', sa.Text(), server_default='', nullable=False),
    sa.Column('strategy', sa.Text(), server_default='', nullable=False),
    sa.Column('script', sa.Text(), server_default='', nullable=False),
    sa.Column('messages', sa.Text(), server_default='[]', nullable=False),
    sa.Column('history', sa.Text(), server_default='[]', nullable=False),
    sa.Column('workflow', sa.Text(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_screenwriting_session_disabled_at'), 'af_screenwriting_session', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_screenwriting_session_isolation_key'), 'af_screenwriting_session', ['isolation_key'], unique=True)
    op.create_index(op.f('ix_af_screenwriting_session_project_id'), 'af_screenwriting_session', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_screenwriting_session_public_id'), 'af_screenwriting_session', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_screenwriting_session_sort_order'), 'af_screenwriting_session', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_screenwriting_session_user_public_id'), 'af_screenwriting_session', ['user_public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_screenwriting_session_user_public_id'), table_name='af_screenwriting_session')
    op.drop_index(op.f('ix_af_screenwriting_session_sort_order'), table_name='af_screenwriting_session')
    op.drop_index(op.f('ix_af_screenwriting_session_public_id'), table_name='af_screenwriting_session')
    op.drop_index(op.f('ix_af_screenwriting_session_project_id'), table_name='af_screenwriting_session')
    op.drop_index(op.f('ix_af_screenwriting_session_isolation_key'), table_name='af_screenwriting_session')
    op.drop_index(op.f('ix_af_screenwriting_session_disabled_at'), table_name='af_screenwriting_session')
    op.drop_table('af_screenwriting_session')
    # ### end Alembic commands ###
