"""add novel table

Revision ID: 8c78a6330420
Revises: 0a337beb460e
Create Date: 2026-07-15 13:17:24.219157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8c78a6330420'
down_revision: Union[str, Sequence[str], None] = '0a337beb460e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_novel_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chapter_index', sa.Integer(), nullable=False),
    sa.Column('reel', sa.String(length=120), server_default='', nullable=False),
    sa.Column('chapter', sa.String(length=255), nullable=False),
    sa.Column('chapter_data', sa.Text(), server_default='', nullable=False),
    sa.Column('event', sa.Text(), server_default='', nullable=False),
    sa.Column('event_state', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('crawl_source_key', sa.String(length=64), server_default='', nullable=False),
    sa.Column('crawl_novel_dirid', sa.String(length=120), server_default='', nullable=False),
    sa.Column('crawl_chapter_id', sa.Integer(), nullable=True),
    sa.Column('crawl_time', sa.String(length=64), server_default='', nullable=False),
    sa.Column('crawl_md5', sa.String(length=64), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_novel_chapter_chapter'), 'af_novel_chapter', ['chapter'], unique=False)
    op.create_index(op.f('ix_af_novel_chapter_chapter_index'), 'af_novel_chapter', ['chapter_index'], unique=False)
    op.create_index(op.f('ix_af_novel_chapter_disabled_at'), 'af_novel_chapter', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_novel_chapter_event_state'), 'af_novel_chapter', ['event_state'], unique=False)
    op.create_index(op.f('ix_af_novel_chapter_project_id'), 'af_novel_chapter', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_novel_chapter_public_id'), 'af_novel_chapter', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_novel_chapter_sort_order'), 'af_novel_chapter', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_novel_chapter_sort_order'), table_name='af_novel_chapter')
    op.drop_index(op.f('ix_af_novel_chapter_public_id'), table_name='af_novel_chapter')
    op.drop_index(op.f('ix_af_novel_chapter_project_id'), table_name='af_novel_chapter')
    op.drop_index(op.f('ix_af_novel_chapter_event_state'), table_name='af_novel_chapter')
    op.drop_index(op.f('ix_af_novel_chapter_disabled_at'), table_name='af_novel_chapter')
    op.drop_index(op.f('ix_af_novel_chapter_chapter_index'), table_name='af_novel_chapter')
    op.drop_index(op.f('ix_af_novel_chapter_chapter'), table_name='af_novel_chapter')
    op.drop_table('af_novel_chapter')
    # ### end Alembic commands ###
