"""add project table

Revision ID: 9d2868652ee5
Revises: b4d6dc639248
Create Date: 2026-05-27 18:51:48.394257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9d2868652ee5'
down_revision: Union[str, Sequence[str], None] = 'b4d6dc639248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('intro', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('project_type', sa.String(length=50), server_default='novel_to_video', nullable=False),
    sa.Column('content_type', sa.String(length=50), server_default='novel', nullable=False),
    sa.Column('art_style', sa.String(length=100), server_default='3D_chinese_traditional', nullable=False),
    sa.Column('director_manual', sa.String(length=4000), server_default='', nullable=False),
    sa.Column('video_ratio', sa.String(length=20), server_default='9:16', nullable=False),
    sa.Column('text_model', sa.String(length=100), server_default='', nullable=False),
    sa.Column('image_model', sa.String(length=100), server_default='', nullable=False),
    sa.Column('video_model', sa.String(length=100), server_default='', nullable=False),
    sa.Column('tts_model', sa.String(length=100), server_default='', nullable=False),
    sa.Column('image_quality', sa.String(length=50), server_default='standard', nullable=False),
    sa.Column('mode', sa.Enum('text', 'singleImage', 'multiReference', 'startEndRequired', 'endFrameOptional', 'startFrameOptional', name='project_video_mode', native_enum=False, create_constraint=True, length=50), server_default='text', nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['af_user.public_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_project_disabled_at'), 'af_project', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_project_name'), 'af_project', ['name'], unique=False)
    op.create_index(op.f('ix_af_project_owner_id'), 'af_project', ['owner_id'], unique=False)
    op.create_index(op.f('ix_af_project_public_id'), 'af_project', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_project_sort_order'), 'af_project', ['sort_order'], unique=False)
    op.create_table('af_project_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'manager', 'editor', 'viewer', name='project_member_role', native_enum=False, create_constraint=True, length=20), server_default='viewer', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.ForeignKeyConstraint(['user_public_id'], ['af_user.public_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_project_member_project_id'), 'af_project_member', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_project_member_user_public_id'), 'af_project_member', ['user_public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_project_member_user_public_id'), table_name='af_project_member')
    op.drop_index(op.f('ix_af_project_member_project_id'), table_name='af_project_member')
    op.drop_table('af_project_member')
    op.drop_index(op.f('ix_af_project_sort_order'), table_name='af_project')
    op.drop_index(op.f('ix_af_project_public_id'), table_name='af_project')
    op.drop_index(op.f('ix_af_project_owner_id'), table_name='af_project')
    op.drop_index(op.f('ix_af_project_name'), table_name='af_project')
    op.drop_index(op.f('ix_af_project_disabled_at'), table_name='af_project')
    op.drop_table('af_project')
    # ### end Alembic commands ###
