"""create user table

Revision ID: b4d6dc639248
Revises: 
Create Date: 2026-05-08 16:05:19.377770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d6dc639248'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_user_disabled_at'), 'af_user', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_user_email'), 'af_user', ['email'], unique=True)
    op.create_index(op.f('ix_af_user_public_id'), 'af_user', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_user_sort_order'), 'af_user', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_user_username'), 'af_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_user_username'), table_name='af_user')
    op.drop_index(op.f('ix_af_user_sort_order'), table_name='af_user')
    op.drop_index(op.f('ix_af_user_public_id'), table_name='af_user')
    op.drop_index(op.f('ix_af_user_email'), table_name='af_user')
    op.drop_index(op.f('ix_af_user_disabled_at'), table_name='af_user')
    op.drop_table('af_user')
    # ### end Alembic commands ###
