"""create project table

Revision ID: c875d2aec966
Revises: 8117da46bf39
Create Date: 2026-05-13 17:03:51.004920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c875d2aec966'
down_revision: Union[str, Sequence[str], None] = '8117da46bf39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('af_project', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.add_column('af_project', sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('af_project', sa.Column('content_type', sa.String(length=50), nullable=False))
    op.alter_column('af_project', 'owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.create_index(op.f('ix_af_project_disabled_at'), 'af_project', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_project_sort_order'), 'af_project', ['sort_order'], unique=False)
    op.create_foreign_key(None, 'af_project', 'af_user', ['owner_id'], ['public_id'])
    op.drop_column('af_project', 'type')
    op.create_foreign_key(None, 'af_project_member', 'af_project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'af_project_member', 'af_user', ['user_public_id'], ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'af_project_member', type_='foreignkey')
    op.drop_constraint(None, 'af_project_member', type_='foreignkey')
    op.add_column('af_project', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'af_project', type_='foreignkey')
    op.drop_index(op.f('ix_af_project_sort_order'), table_name='af_project')
    op.drop_index(op.f('ix_af_project_disabled_at'), table_name='af_project')
    op.alter_column('af_project', 'owner_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('af_project', 'content_type')
    op.drop_column('af_project', 'disabled_at')
    op.drop_column('af_project', 'sort_order')
    # ### end Alembic commands ###
