"""add novel crawler table

Revision ID: d2a8eda0aa36
Revises: 8c78a6330420
Create Date: 2026-07-15 13:51:58.857660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd2a8eda0aa36'
down_revision: Union[str, Sequence[str], None] = '8c78a6330420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_novel_crawl_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('source_book_id', sa.String(length=120), nullable=False),
    sa.Column('source_book_numeric_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=120), server_default='', nullable=False),
    sa.Column('cover_url', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('category', sa.String(length=120), server_default='', nullable=False),
    sa.Column('update_status', sa.String(length=120), server_default='', nullable=False),
    sa.Column('intro', sa.Text(), server_default='', nullable=False),
    sa.Column('last_chapter', sa.String(length=255), server_default='', nullable=False),
    sa.Column('last_chapter_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_update', sa.String(length=64), server_default='', nullable=False),
    sa.Column('raw_data', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_key', 'source_book_id', name='uq_af_novel_crawl_book_project_source_book')
    )
    op.create_index(op.f('ix_af_novel_crawl_book_author'), 'af_novel_crawl_book', ['author'], unique=False)
    op.create_index(op.f('ix_af_novel_crawl_book_category'), 'af_novel_crawl_book', ['category'], unique=False)
    op.create_index(op.f('ix_af_novel_crawl_book_disabled_at'), 'af_novel_crawl_book', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_novel_crawl_book_project_id'), 'af_novel_crawl_book', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_novel_crawl_book_public_id'), 'af_novel_crawl_book', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_novel_crawl_book_sort_order'), 'af_novel_crawl_book', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_novel_crawl_book_source_book_id'), 'af_novel_crawl_book', ['source_book_id'], unique=False)
    op.create_index(op.f('ix_af_novel_crawl_book_source_key'), 'af_novel_crawl_book', ['source_key'], unique=False)
    op.create_index(op.f('ix_af_novel_crawl_book_title'), 'af_novel_crawl_book', ['title'], unique=False)
    op.create_table('af_novel_crawl_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('owner_public_id', sa.String(length=36), server_default='', nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('desc', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('builtin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_type', sa.String(length=20), server_default='api', nullable=False),
    sa.Column('scope', sa.String(length=20), server_default='private', nullable=False),
    sa.Column('search_url_template', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('api_search_method', sa.String(length=10), server_default='GET', nullable=False),
    sa.Column('api_search_headers', sa.Text(), server_default='', nullable=False),
    sa.Column('api_search_body', sa.Text(), server_default='', nullable=False),
    sa.Column('api_search_book_url_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_search_book_id_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_search_book_title_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_search_book_author_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_search_book_intro_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_search_book_cover_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_search_book_category_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_search_book_update_status_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_search_book_last_chapter_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_search_book_last_chapter_id_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_search_book_last_update_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_book_url', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('api_book_method', sa.String(length=10), server_default='GET', nullable=False),
    sa.Column('api_book_headers', sa.Text(), server_default='', nullable=False),
    sa.Column('api_book_body', sa.Text(), server_default='', nullable=False),
    sa.Column('api_book_title_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_book_author_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_book_intro_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_book_last_chapter_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_book_last_chapter_id_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_book_last_update_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_book_cover_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_book_category_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_book_update_status_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_book_id_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_chapter_list_url', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('api_chapter_list_method', sa.String(length=10), server_default='GET', nullable=False),
    sa.Column('api_chapter_list_headers', sa.Text(), server_default='', nullable=False),
    sa.Column('api_chapter_list_body', sa.Text(), server_default='', nullable=False),
    sa.Column('api_chapter_list_id_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_chapter_list_name_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_chapter_list_time_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_chapter_list_content_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_chapter_list_md5_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_chapter_url', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('api_chapter_method', sa.String(length=10), server_default='GET', nullable=False),
    sa.Column('api_chapter_headers', sa.Text(), server_default='', nullable=False),
    sa.Column('api_chapter_body', sa.Text(), server_default='', nullable=False),
    sa.Column('api_chapter_name_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_chapter_content_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_chapter_time_path', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('api_chapter_md5_path', sa.String(length=1000), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_novel_crawl_source_disabled_at'), 'af_novel_crawl_source', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_novel_crawl_source_key'), 'af_novel_crawl_source', ['key'], unique=True)
    op.create_index(op.f('ix_af_novel_crawl_source_name'), 'af_novel_crawl_source', ['name'], unique=False)
    op.create_index(op.f('ix_af_novel_crawl_source_owner_public_id'), 'af_novel_crawl_source', ['owner_public_id'], unique=False)
    op.create_index(op.f('ix_af_novel_crawl_source_project_id'), 'af_novel_crawl_source', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_novel_crawl_source_public_id'), 'af_novel_crawl_source', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_novel_crawl_source_scope'), 'af_novel_crawl_source', ['scope'], unique=False)
    op.create_index(op.f('ix_af_novel_crawl_source_sort_order'), 'af_novel_crawl_source', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_novel_crawl_source_sort_order'), table_name='af_novel_crawl_source')
    op.drop_index(op.f('ix_af_novel_crawl_source_scope'), table_name='af_novel_crawl_source')
    op.drop_index(op.f('ix_af_novel_crawl_source_public_id'), table_name='af_novel_crawl_source')
    op.drop_index(op.f('ix_af_novel_crawl_source_project_id'), table_name='af_novel_crawl_source')
    op.drop_index(op.f('ix_af_novel_crawl_source_owner_public_id'), table_name='af_novel_crawl_source')
    op.drop_index(op.f('ix_af_novel_crawl_source_name'), table_name='af_novel_crawl_source')
    op.drop_index(op.f('ix_af_novel_crawl_source_key'), table_name='af_novel_crawl_source')
    op.drop_index(op.f('ix_af_novel_crawl_source_disabled_at'), table_name='af_novel_crawl_source')
    op.drop_table('af_novel_crawl_source')
    op.drop_index(op.f('ix_af_novel_crawl_book_title'), table_name='af_novel_crawl_book')
    op.drop_index(op.f('ix_af_novel_crawl_book_source_key'), table_name='af_novel_crawl_book')
    op.drop_index(op.f('ix_af_novel_crawl_book_source_book_id'), table_name='af_novel_crawl_book')
    op.drop_index(op.f('ix_af_novel_crawl_book_sort_order'), table_name='af_novel_crawl_book')
    op.drop_index(op.f('ix_af_novel_crawl_book_public_id'), table_name='af_novel_crawl_book')
    op.drop_index(op.f('ix_af_novel_crawl_book_project_id'), table_name='af_novel_crawl_book')
    op.drop_index(op.f('ix_af_novel_crawl_book_disabled_at'), table_name='af_novel_crawl_book')
    op.drop_index(op.f('ix_af_novel_crawl_book_category'), table_name='af_novel_crawl_book')
    op.drop_index(op.f('ix_af_novel_crawl_book_author'), table_name='af_novel_crawl_book')
    op.drop_table('af_novel_crawl_book')
    # ### end Alembic commands ###
