"""add_script_plan_and_episode_tables

Revision ID: d870b826d913
Revises: 876790dceb98
Create Date: 2026-07-16 17:21:11.751507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd870b826d913'
down_revision: Union[str, Sequence[str], None] = '876790dceb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_script_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.String(length=36), nullable=False),
    sa.Column('source_isolation_key', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=200), server_default='', nullable=False),
    sa.Column('total_episodes', sa.String(length=60), server_default='', nullable=False),
    sa.Column('episode_duration', sa.String(length=60), server_default='', nullable=False),
    sa.Column('source_range', sa.String(length=120), server_default='', nullable=False),
    sa.Column('platform_spec', sa.String(length=120), server_default='', nullable=False),
    sa.Column('style', sa.String(length=200), server_default='', nullable=False),
    sa.Column('paywall', sa.String(length=200), server_default='', nullable=False),
    sa.Column('status', sa.String(length=40), server_default='synced', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['af_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_script_plan_disabled_at'), 'af_script_plan', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_script_plan_project_id'), 'af_script_plan', ['project_id'], unique=False)
    op.create_index(op.f('ix_af_script_plan_public_id'), 'af_script_plan', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_script_plan_sort_order'), 'af_script_plan', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_script_plan_source_isolation_key'), 'af_script_plan', ['source_isolation_key'], unique=True)
    op.create_index(op.f('ix_af_script_plan_user_public_id'), 'af_script_plan', ['user_public_id'], unique=False)
    op.create_table('af_script_episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('episode_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), server_default='', nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('scenes', sa.Text(), server_default='[]', nullable=False),
    sa.Column('chapter_ids', sa.String(length=400), server_default='', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_locked', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['af_script_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'episode_index', name='uq_script_episode_plan_index')
    )
    op.create_index(op.f('ix_af_script_episode_disabled_at'), 'af_script_episode', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_script_episode_episode_index'), 'af_script_episode', ['episode_index'], unique=False)
    op.create_index(op.f('ix_af_script_episode_plan_id'), 'af_script_episode', ['plan_id'], unique=False)
    op.create_index(op.f('ix_af_script_episode_public_id'), 'af_script_episode', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_script_episode_sort_order'), 'af_script_episode', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_script_episode_sort_order'), table_name='af_script_episode')
    op.drop_index(op.f('ix_af_script_episode_public_id'), table_name='af_script_episode')
    op.drop_index(op.f('ix_af_script_episode_plan_id'), table_name='af_script_episode')
    op.drop_index(op.f('ix_af_script_episode_episode_index'), table_name='af_script_episode')
    op.drop_index(op.f('ix_af_script_episode_disabled_at'), table_name='af_script_episode')
    op.drop_table('af_script_episode')
    op.drop_index(op.f('ix_af_script_plan_user_public_id'), table_name='af_script_plan')
    op.drop_index(op.f('ix_af_script_plan_source_isolation_key'), table_name='af_script_plan')
    op.drop_index(op.f('ix_af_script_plan_sort_order'), table_name='af_script_plan')
    op.drop_index(op.f('ix_af_script_plan_public_id'), table_name='af_script_plan')
    op.drop_index(op.f('ix_af_script_plan_project_id'), table_name='af_script_plan')
    op.drop_index(op.f('ix_af_script_plan_disabled_at'), table_name='af_script_plan')
    op.drop_table('af_script_plan')
    # ### end Alembic commands ###
