"""create task table

Revision ID: e107d7f2328d
Revises: d2a8eda0aa36
Create Date: 2026-07-15 15:59:29.832815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e107d7f2328d'
down_revision: Union[str, Sequence[str], None] = 'd2a8eda0aa36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_task_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('queue_name', sa.String(length=120), server_default='default', nullable=False),
    sa.Column('name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'succeeded', 'failed', 'cancelled', 'partial', 'paused', name='task_status', native_enum=False, create_constraint=True, length=20), server_default='pending', nullable=False),
    sa.Column('created_by', sa.String(length=36), server_default='', nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), server_default='', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed_items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cancelled_items', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', sa.Text(), server_default='{}', nullable=False),
    sa.Column('result', sa.Text(), server_default='{}', nullable=False),
    sa.Column('error_code', sa.String(length=100), server_default='', nullable=False),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_task_job_created_by'), 'af_task_job', ['created_by'], unique=False)
    op.create_index(op.f('ix_af_task_job_disabled_at'), 'af_task_job', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_task_job_idempotency_key'), 'af_task_job', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_af_task_job_priority'), 'af_task_job', ['priority'], unique=False)
    op.create_index(op.f('ix_af_task_job_public_id'), 'af_task_job', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_task_job_queue_name'), 'af_task_job', ['queue_name'], unique=False)
    op.create_index(op.f('ix_af_task_job_scheduled_at'), 'af_task_job', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_af_task_job_sort_order'), 'af_task_job', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_task_job_status'), 'af_task_job', ['status'], unique=False)
    op.create_index(op.f('ix_af_task_job_task_type'), 'af_task_job', ['task_type'], unique=False)
    op.create_table('af_task_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=100), server_default='', nullable=False),
    sa.Column('item_key', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'succeeded', 'failed', 'cancelled', 'partial', 'paused', name='task_status', native_enum=False, create_constraint=True, length=20), server_default='pending', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('worker_id', sa.String(length=120), server_default='', nullable=False),
    sa.Column('payload', sa.Text(), server_default='{}', nullable=False),
    sa.Column('result', sa.Text(), server_default='{}', nullable=False),
    sa.Column('error_code', sa.String(length=100), server_default='', nullable=False),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['af_task_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'item_key', name='uq_af_task_item_job_item_key')
    )
    op.create_index(op.f('ix_af_task_item_disabled_at'), 'af_task_item', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_af_task_item_item_key'), 'af_task_item', ['item_key'], unique=False)
    op.create_index(op.f('ix_af_task_item_item_type'), 'af_task_item', ['item_type'], unique=False)
    op.create_index(op.f('ix_af_task_item_job_id'), 'af_task_item', ['job_id'], unique=False)
    op.create_index(op.f('ix_af_task_item_priority'), 'af_task_item', ['priority'], unique=False)
    op.create_index(op.f('ix_af_task_item_public_id'), 'af_task_item', ['public_id'], unique=True)
    op.create_index(op.f('ix_af_task_item_scheduled_at'), 'af_task_item', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_af_task_item_sort_order'), 'af_task_item', ['sort_order'], unique=False)
    op.create_index(op.f('ix_af_task_item_status'), 'af_task_item', ['status'], unique=False)
    op.create_index(op.f('ix_af_task_item_worker_id'), 'af_task_item', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_task_item_worker_id'), table_name='af_task_item')
    op.drop_index(op.f('ix_af_task_item_status'), table_name='af_task_item')
    op.drop_index(op.f('ix_af_task_item_sort_order'), table_name='af_task_item')
    op.drop_index(op.f('ix_af_task_item_scheduled_at'), table_name='af_task_item')
    op.drop_index(op.f('ix_af_task_item_public_id'), table_name='af_task_item')
    op.drop_index(op.f('ix_af_task_item_priority'), table_name='af_task_item')
    op.drop_index(op.f('ix_af_task_item_job_id'), table_name='af_task_item')
    op.drop_index(op.f('ix_af_task_item_item_type'), table_name='af_task_item')
    op.drop_index(op.f('ix_af_task_item_item_key'), table_name='af_task_item')
    op.drop_index(op.f('ix_af_task_item_disabled_at'), table_name='af_task_item')
    op.drop_table('af_task_item')
    op.drop_index(op.f('ix_af_task_job_task_type'), table_name='af_task_job')
    op.drop_index(op.f('ix_af_task_job_status'), table_name='af_task_job')
    op.drop_index(op.f('ix_af_task_job_sort_order'), table_name='af_task_job')
    op.drop_index(op.f('ix_af_task_job_scheduled_at'), table_name='af_task_job')
    op.drop_index(op.f('ix_af_task_job_queue_name'), table_name='af_task_job')
    op.drop_index(op.f('ix_af_task_job_public_id'), table_name='af_task_job')
    op.drop_index(op.f('ix_af_task_job_priority'), table_name='af_task_job')
    op.drop_index(op.f('ix_af_task_job_idempotency_key'), table_name='af_task_job')
    op.drop_index(op.f('ix_af_task_job_disabled_at'), table_name='af_task_job')
    op.drop_index(op.f('ix_af_task_job_created_by'), table_name='af_task_job')
    op.drop_table('af_task_job')
    # ### end Alembic commands ###
